data:
  dir: datasets/vangogh2photo
  size: 256
  nc_A: 3             # number of channels in domain A
  nc_B: 3             # number of channels in domain B

model:
  ngf: 64             # number of generator filters in the last conv. layer
  ndf: 64             # number of discriminator filters in the first conv. layer
  n_res_blocks: 9     # number of residual blocks in generator
  n_D_layers: 3       # number of convolution layers in discriminator
  lambda_A: 10
  lambda_B: 10
  lambda_idt: 0.25

train:
  train_epoch_num: 100000
  start_learning_rate_D: 0.0003
  end_learning_rate_D: 0.0001
  start_learning_rate_G: 0.0002
  end_learning_rate_G: 0.0001
  batch_size: 1

  log_dir: logs/v4
  chkpt_dir: chkpt/v4
  summary_interval: 1
  loss_evaluation_interval: 1000
  sample_evaluation_interval: 1000
  save_chkpt_interval: 10000

